EMAILS = [
    {"email_id": "e001", "subject": "Congratulations! You won $1,000,000", "body": "Dear user, you have been selected as our lucky winner. Click here to claim your prize now. Limited time offer!", "sender": "winner@totally-legit.xyz", "label": "spam", "priority": "low", "category": "other", "ideal_reply_keywords": []},
    {"email_id": "e002", "subject": "My invoice is wrong", "body": "Hi, I was charged $120 but the agreed price was $90. Please fix this as soon as possible. I need this resolved urgently.", "sender": "customer1@gmail.com", "label": "not_spam", "priority": "urgent", "category": "billing", "ideal_reply_keywords": ["sorry", "invoice", "fix", "refund", "team"]},
    {"email_id": "e003", "subject": "Question about your product", "body": "Hello, I was wondering if your software supports Linux. I am considering purchasing but need to confirm compatibility first.", "sender": "potential.buyer@outlook.com", "label": "not_spam", "priority": "normal", "category": "support", "ideal_reply_keywords": ["linux", "support", "compatible", "help"]},
    {"email_id": "e004", "subject": "FREE VIAGRA - LIMITED OFFER", "body": "Buy now get 90% off. No prescription needed. Click the link below.", "sender": "deals@spammy-pharma.ru", "label": "spam", "priority": "low", "category": "other", "ideal_reply_keywords": []},
    {"email_id": "e005", "subject": "Feedback on recent experience", "body": "I recently used your service and wanted to share some thoughts. Overall it was good but the onboarding could be smoother.", "sender": "happy.user@yahoo.com", "label": "not_spam", "priority": "low", "category": "feedback", "ideal_reply_keywords": ["thank", "feedback", "improve", "appreciate"]},
    {"email_id": "e006", "subject": "Account suspended without warning", "body": "My account was suspended this morning and I have no idea why. I rely on this for my business. Please restore it immediately.", "sender": "angry.biz@company.com", "label": "not_spam", "priority": "urgent", "category": "support", "ideal_reply_keywords": ["sorry", "account", "investigate", "restore", "team"]},
    {"email_id": "e007", "subject": "You have been pre-approved for a loan", "body": "No credit check needed. Get $50,000 deposited to your account today. Reply with your bank details.", "sender": "loans@fast-cash-now.biz", "label": "spam", "priority": "low", "category": "other", "ideal_reply_keywords": []},
    {"email_id": "e008", "subject": "Billing cycle question", "body": "Hi there, I noticed my billing cycle changed from monthly to annual without my consent. Can you clarify and offer a refund?", "sender": "user.billing@hotmail.com", "label": "not_spam", "priority": "urgent", "category": "billing", "ideal_reply_keywords": ["billing", "cycle", "refund", "sorry", "review"]},
    {"email_id": "e009", "subject": "Great product, small suggestion", "body": "Love what you guys are building. One small thing - it would be great if dark mode was available on mobile too.", "sender": "fan.user@gmail.com", "label": "not_spam", "priority": "low", "category": "feedback", "ideal_reply_keywords": ["thank", "dark mode", "note", "team", "appreciate"]},
    {"email_id": "e010", "subject": "Cannot login to my account", "body": "I have been trying to login for the past 2 hours and keep getting an error. I have already reset my password twice.", "sender": "stuck.user@gmail.com", "label": "not_spam", "priority": "urgent", "category": "support", "ideal_reply_keywords": ["login", "error", "help", "team", "sorry", "investigate"]},
]
